spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
          num-ctx: 5096
    openai:
      api-key: xyz123

chatbot:
  pdf:
   lib: itext 
   #lib: pdfbox
   #lib: openpdf